#!/bin/sh
sep=$1
col1=$2
col2=$3
awk -F$sep 'pass==1 {sx+=$'$col1'; sy+=$'$col2'; n+=1} 
		 				pass==2 {mx=sx/(n-1); my=sy/(n-1); cov+=($'$col1'-mx)*($'$col2'-my); ssdx+=($'$col1'-mx)*($'$col1'-mx); ssdy+=($'$col2'-my)*($'$col2'-my);} 
		 				END {print cov / ( sqrt(ssdx) * sqrt(ssdy) ) }' pass=1 $4 pass=2 $4
